-- Create table to track commission rate history per staff member
CREATE TABLE public.staff_commission_rate_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id UUID NOT NULL,
  commission_rate NUMERIC(5,2) NOT NULL,
  commission_basis TEXT NOT NULL CHECK (commission_basis IN ('revenue', 'profit')),
  effective_from TIMESTAMPTZ NOT NULL DEFAULT now(),
  effective_to TIMESTAMPTZ NULL, -- NULL means currently active
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_by UUID
);

-- Index for efficient lookups by staff and date range
CREATE INDEX idx_commission_rate_history_staff_dates 
ON public.staff_commission_rate_history(staff_id, effective_from, effective_to);

-- Enable RLS
ALTER TABLE public.staff_commission_rate_history ENABLE ROW LEVEL SECURITY;

-- Owners can manage all rate history
CREATE POLICY "Owners can manage commission rate history" 
ON public.staff_commission_rate_history FOR ALL 
USING (is_owner(auth.uid()))
WITH CHECK (is_owner(auth.uid()));

-- Staff can view their own rate history
CREATE POLICY "Staff can view own rate history" 
ON public.staff_commission_rate_history FOR SELECT 
USING (auth.uid() = staff_id);

-- Migrate existing overrides to history table
INSERT INTO public.staff_commission_rate_history (staff_id, commission_rate, commission_basis, effective_from, notes, created_at, created_by)
SELECT 
  staff_id,
  commission_rate,
  commission_basis,
  created_at, -- Use the original created_at as effective_from
  notes,
  now(),
  created_by
FROM public.staff_commission_overrides;