-- Add new stock movement types for deposit orders
ALTER TYPE stock_movement_type ADD VALUE IF NOT EXISTS 'reserve';
ALTER TYPE stock_movement_type ADD VALUE IF NOT EXISTS 'release';

-- Create deposit_orders table
CREATE TABLE public.deposit_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id bigint NOT NULL REFERENCES public.customers(id),
  customer_name text NOT NULL,
  staff_id uuid REFERENCES auth.users(id),
  location_id bigint REFERENCES public.locations(id),
  total_amount numeric NOT NULL DEFAULT 0,
  amount_paid numeric NOT NULL DEFAULT 0,
  balance_due numeric GENERATED ALWAYS AS (total_amount - amount_paid) STORED,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'cancelled', 'expired')),
  notes text,
  expected_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  completed_by uuid REFERENCES auth.users(id),
  sale_id bigint REFERENCES public.sales(id),
  demo_session_id text
);

-- Create deposit_order_items table
CREATE TABLE public.deposit_order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deposit_order_id bigint NOT NULL REFERENCES public.deposit_orders(id) ON DELETE CASCADE,
  product_id bigint REFERENCES public.products(id),
  product_name text NOT NULL,
  unit_price numeric NOT NULL DEFAULT 0,
  unit_cost numeric NOT NULL DEFAULT 0,
  quantity integer NOT NULL DEFAULT 1,
  is_custom_order boolean NOT NULL DEFAULT false,
  reserved_at timestamp with time zone DEFAULT now()
);

-- Create deposit_payments table
CREATE TABLE public.deposit_payments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  deposit_order_id bigint NOT NULL REFERENCES public.deposit_orders(id) ON DELETE CASCADE,
  amount numeric NOT NULL,
  payment_method payment_method NOT NULL DEFAULT 'cash',
  received_by uuid REFERENCES auth.users(id),
  received_at timestamp with time zone NOT NULL DEFAULT now(),
  notes text
);

-- Create indexes for performance
CREATE INDEX idx_deposit_orders_customer ON public.deposit_orders(customer_id);
CREATE INDEX idx_deposit_orders_status ON public.deposit_orders(status);
CREATE INDEX idx_deposit_orders_staff ON public.deposit_orders(staff_id);
CREATE INDEX idx_deposit_order_items_order ON public.deposit_order_items(deposit_order_id);
CREATE INDEX idx_deposit_order_items_product ON public.deposit_order_items(product_id);
CREATE INDEX idx_deposit_payments_order ON public.deposit_payments(deposit_order_id);

-- Enable RLS on all tables
ALTER TABLE public.deposit_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deposit_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deposit_payments ENABLE ROW LEVEL SECURITY;

-- RLS policies for deposit_orders
CREATE POLICY "Staff can view all deposit orders"
  ON public.deposit_orders FOR SELECT
  USING (is_staff(auth.uid()));

CREATE POLICY "Staff can create deposit orders"
  ON public.deposit_orders FOR INSERT
  WITH CHECK (is_staff(auth.uid()));

CREATE POLICY "Owners and managers can update deposit orders"
  ON public.deposit_orders FOR UPDATE
  USING (is_owner_or_manager(auth.uid()));

CREATE POLICY "Owners can delete deposit orders"
  ON public.deposit_orders FOR DELETE
  USING (is_owner(auth.uid()));

-- RLS policies for deposit_order_items
CREATE POLICY "Staff can view deposit order items"
  ON public.deposit_order_items FOR SELECT
  USING (is_staff(auth.uid()));

CREATE POLICY "Staff can create deposit order items"
  ON public.deposit_order_items FOR INSERT
  WITH CHECK (is_staff(auth.uid()));

CREATE POLICY "Owners and managers can update deposit order items"
  ON public.deposit_order_items FOR UPDATE
  USING (is_owner_or_manager(auth.uid()));

CREATE POLICY "Owners can delete deposit order items"
  ON public.deposit_order_items FOR DELETE
  USING (is_owner(auth.uid()));

-- RLS policies for deposit_payments
CREATE POLICY "Staff can view deposit payments"
  ON public.deposit_payments FOR SELECT
  USING (is_staff(auth.uid()));

CREATE POLICY "Staff can create deposit payments"
  ON public.deposit_payments FOR INSERT
  WITH CHECK (is_staff(auth.uid()));

CREATE POLICY "Owners and managers can update deposit payments"
  ON public.deposit_payments FOR UPDATE
  USING (is_owner_or_manager(auth.uid()));

CREATE POLICY "Owners can delete deposit payments"
  ON public.deposit_payments FOR DELETE
  USING (is_owner(auth.uid()));

-- Create summary view for deposit orders (using dord alias instead of do which is reserved)
CREATE OR REPLACE VIEW public.v_deposit_order_summary AS
SELECT 
  dord.id,
  dord.customer_id,
  dord.customer_name,
  dord.staff_id,
  prof.full_name as staff_name,
  dord.location_id,
  loc.name as location_name,
  dord.total_amount,
  dord.amount_paid,
  dord.balance_due,
  dord.status,
  dord.notes,
  dord.expected_date,
  dord.created_at,
  dord.completed_at,
  dord.sale_id,
  COUNT(DISTINCT doi.id) as item_count,
  STRING_AGG(DISTINCT doi.product_name, ', ') as item_names,
  COUNT(DISTINCT dp.id) as payment_count,
  MAX(dp.received_at) as last_payment_at
FROM public.deposit_orders dord
LEFT JOIN public.deposit_order_items doi ON doi.deposit_order_id = dord.id
LEFT JOIN public.deposit_payments dp ON dp.deposit_order_id = dord.id
LEFT JOIN public.profiles prof ON prof.user_id = dord.staff_id
LEFT JOIN public.locations loc ON loc.id = dord.location_id
GROUP BY dord.id, dord.customer_id, dord.customer_name, dord.staff_id, prof.full_name,
         dord.location_id, loc.name, dord.total_amount, dord.amount_paid, dord.balance_due,
         dord.status, dord.notes, dord.expected_date, dord.created_at, dord.completed_at, dord.sale_id;

-- Create function to update amount_paid when payments change
CREATE OR REPLACE FUNCTION public.update_deposit_amount_paid()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    UPDATE public.deposit_orders
    SET amount_paid = COALESCE((
      SELECT SUM(amount) FROM public.deposit_payments WHERE deposit_order_id = OLD.deposit_order_id
    ), 0)
    WHERE id = OLD.deposit_order_id;
    RETURN OLD;
  ELSE
    UPDATE public.deposit_orders
    SET amount_paid = COALESCE((
      SELECT SUM(amount) FROM public.deposit_payments WHERE deposit_order_id = NEW.deposit_order_id
    ), 0)
    WHERE id = NEW.deposit_order_id;
    RETURN NEW;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Create trigger to auto-update amount_paid
CREATE TRIGGER trg_update_deposit_amount_paid
AFTER INSERT OR UPDATE OR DELETE ON public.deposit_payments
FOR EACH ROW EXECUTE FUNCTION public.update_deposit_amount_paid();