// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmntylkvmswrtgntlznu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtbnR5bGt2bXN3cnRnbnRsem51Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzODA5NTAsImV4cCI6MjA4NTk1Njk1MH0.DzTpDGXNGMRbYIuZ7ERImsHmLMQuudEkFwoh3m74ais";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});